version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=property_db
      - POSTG-RES_USER=property_user
      - POSTGRES_PASSWORD=property_pass
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data: